### ISSUE TITLE
[Error]KeyError: ' token'

### ISSUE THREAD

**Issue by Abs-11001** [ZainCheung/netease-cloud#1]
大佬您好，我把这个项目放到了我的服务器上，产生了如下问题，请问该如何解决？谢谢
![image](https://user-images.githubusercontent.com/61892708/85940501-5fdb8b80-b94f-11ea-9760-f29c4e45b01f.png)

**Comment by ZainCheung** [comment]
> 大佬您好，我把这个项目放到了我的服务器上，产生了如下问题，请问该如何解决？谢谢
> ![image](https://user-images.githubusercontent.com/61892708/85940501-5fdb8b80-b94f-11ea-9760-f29c4e45b01f.png)

我看不到你的图啊

**Comment by Abs-11001** [comment]
> > 大佬您好，我把这个项目放到了我的服务器上，产生了如下问题，请问该如何解决？谢谢
> > ![image](https://user-images.githubusercontent.com/61892708/85940501-5fdb8b80-b94f-11ea-9760-f29c4e45b01f.png)
> 
> 我看不到你的图啊

root@iZ7 gwdvtc37sg4Z:~# /usr/bin/ python3.6 /home/ python/ c1oud/ main. py
Exception in thread Thread-1:
Traceback (most recent call last) :
File” /usr/1ib/python3.6/threading.py", line 916, in_ bootstrap _innel
self . run( )
File” /usr/1ib/python3.6/threading.py", line 1182, in run
self . function(*self .args, **se1f . kwargs )
File "/home/ python/ c1oud/main.py"s line 247」 in taskPoo1 
config = init( )
File "/home/ python/ c1oud/main.py"s 1ine 192」 in init
config[ 'token' ][ ' account']
File” /usr/1ib/python3.6/configparser .py", line 959, in_ getitem__
raise KeyError(key)
KeyError: ' token'

**Comment by Abs-11001** [comment]
root@iZ7 gwdvtc37sg4Z:~# /usr/bin/ python3.6 /home/ python/ c1oud/ main. py
Exception in thread Thread-1:
Traceback (most recent call last) :
File” /usr/1ib/python3.6/threading.py", line 916, in_ bootstrap _innel
self . run( )
File” /usr/1ib/python3.6/threading.py", line 1182, in run
self . function(*self .args, **se1f . kwargs )
File "/home/ python/ c1oud/main.py"s line 247」 in taskPoo1&nbsp;
config = init( )
File "/home/ python/ c1oud/main.py"s 1ine 192」 in init
config[ 'token' ][ ' account']
File” /usr/1ib/python3.6/configparser .py", line 959, in_ getitem__
raise KeyError(key)
KeyError: ' token'







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zain"<notifications@github.com&gt;; 
发送时间: 2020年6月28日(星期天) 下午2:59
收件人: "ZainCheung/netease-cloud"<netease-cloud@noreply.github.com&gt;; 
抄送: "1196399230"<1196399230@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ZainCheung/netease-cloud] 报错了 (#1)





  
大佬您好，我把这个项目放到了我的服务器上，产生了如下问题，请问该如何解决？谢谢
 
  
我看不到你的图啊

**Comment by ZainCheung** [comment]
> > > 大佬您好，我把这个项目放到了我的服务器上，产生了如下问题，请问该如何解决？谢谢
> > > ![image](https://user-images.githubusercontent.com/61892708/85940501-5fdb8b80-b94f-11ea-9760-f29c4e45b01f.png)
> > 
> > 
> > 我看不到你的图啊
> 
> root@iZ7 gwdvtc37sg4Z:~# /usr/bin/ python3.6 /home/ python/ c1oud/ main. py
> Exception in thread Thread-1:
> Traceback (most recent call last) :
> File” /usr/1ib/python3.6/threading.py", line 916, in_ bootstrap _innel self . run( ) File” /usr/1ib/python3.6/threading.py", line 1182, in run self . function(*self .args, **se1f . kwargs ) File "/home/ python/ c1oud/main.py"s line 247」 in taskPoo1 config = init( ) File "/home/ python/ c1oud/main.py"s 1ine 192」 in init config[ 'token' ][ ' account'] File” /usr/1ib/python3.6/configparser .py", line 959, in_ getitem__
> raise KeyError(key)
> KeyError: ' token'

配置文件你是不是改错了，只能改后面的值，不能改键值对的键，你看下

**Comment by Abs-11001** [comment]
没有  我在本地运行成功了就直接复制到服务器

**Comment by ZainCheung** [comment]
给python升级到3.7.2试试

**Comment by ZainCheung** [comment]
在第190行左右有个init函数，你试着给改成这样，注释可以删掉
`def init():
    global api # 初始化时设置api
    config = ConfigParser()
    config.read('init.config', encoding='UTF-8')
    # uin = config['token']['account']
    # pwd = config['token']['password']
    # api = config['setting']['api']
    # sckey = config['setting']['sckey']
    uin = config.get('token','account')
    pwd = config.get('token','password')
    api = config.get('setting','api')
    sckey = config.get('setting','sckey')
    md5Switch = config.getboolean('setting','md5Switch')
    peopleSwitch = config.getboolean('setting','peopleSwitch')
     
    print('配置文件读取完毕')
    logging.info('配置文件读取完毕')
    conf = {
            'uin': uin,
            'pwd': pwd,
            'api': api,
            'md5Switch': md5Switch, 
            'peopleSwitch':peopleSwitch,
            'sckey':sckey
        }
    return conf`

**Comment by Abs-11001** [comment]
大佬不好意思  没注意到消息  问题找到了   在服务器里面配置文件路径要写绝对路径，相对路径找不到，改成绝对路径没问题了，还有 api是挂了么？

**Comment by BoyceLig** [comment]
> 大佬不好意思 没注意到消息 问题找到了 在服务器里面配置文件路径要写绝对路径，相对路径找不到，改成绝对路径没问题了，还有 api是挂了么？

我搭建了一个api，可以用我的，我的就我一个人用https://netease-cloud-api-boyce.glitch.me/
