### ISSUE TITLE
函数执行错误，求解决

### ISSUE THREAD

**Issue by xmpf7973** [ZainCheung/netease-cloud#10]
如图
![S00709-14550898](https://user-images.githubusercontent.com/57211850/87007338-aef9aa00-c1f4-11ea-8da6-b8b30002c023.jpg)

**Comment by xmpf7973** [comment]
按着教程来的，试了好几次都是这样报错

**Comment by ZainCheung** [comment]
看错误报告不是代码的问题，部署的锅，建议跟着教程再核对一遍部署流程，注意细节

**Comment by xmpf7973** [comment]
> 看错误报告不是代码的问题，部署的锅，建议跟着教程再核对一遍部署流程，注意细节

部署只有那几步，都是按着顺序来的，试了几十次就是不成功

**Comment by xmpf7973** [comment]
> 看错误报告不是代码的问题，部署的锅，建议跟着教程再核对一遍部署流程，注意细节

您能帮我看看吗?

**Comment by xmpf7973** [comment]
> 看错误报告不是代码的问题，部署的锅，建议跟着教程再核对一遍部署流程，注意细节

问题找到了，部署没问题，换个号就好了?hhh

**Comment by ZainCheung** [comment]
好的

**Comment by xmpf7973** [comment]
> 好的

这个bug就离谱

**Comment by ZainCheung** [comment]
账号BUG确实无解。。。

**Comment by Cowan97** [comment]
> 账号BUG确实无解。。。

我只有第一次成功了，后面也报这个错误代码。。。

**Comment by 1915126797** [comment]
提示密码错误咋整？测试的时候是成功了的，第二天自动执行的时候提示密码错误。我用的是云函数版

**Comment by xmpf7973** [comment]
> 提示密码错误咋整？测试的时候是成功了的，第二天自动执行的时候提示密码错误。我用的是云函数版

重新写下密码md5

**Comment by ZainCheung** [comment]
> 提示密码错误咋整？测试的时候是成功了的，第二天自动执行的时候提示密码错误。我用的是云函数版

换个快点的API试试

**Comment by 1915126797** [comment]
谢谢大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zain"<notifications@github.com&gt;; 
发送时间: 2020年7月27日(星期一) 上午9:22
收件人: "ZainCheung/netease-cloud"<netease-cloud@noreply.github.com&gt;; 
抄送: "1915126797"<1915126797@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ZainCheung/netease-cloud] 函数执行错误，求解决 (#10)





  
提示密码错误咋整？测试的时候是成功了的，第二天自动执行的时候提示密码错误。我用的是云函数版
  
换个快点的API试试
