### ISSUE TITLE
多人账号出问题

### ISSUE THREAD

**Issue by yinghuo666** [ZainCheung/netease-cloud#13]
![Uploading YWLIFDXL(A]1~EYR3D)}M`D.png…]()
a71a00-caca-11ea-940c-19b54dc320ba.png

)

单账号测试没问题，试了几个api没有变化，求解

**Comment by yinghuo666** [comment]
https://s1.ax1x.com/2020/07/20/U44eS0.png
https://s1.ax1x.com/2020/07/20/U44mlV.png图在这

**Comment by ZainCheung** [comment]
json格式错了，第一行删去，空行也删去，json不是代码文件，没有注释这一说

**Comment by yinghuo666** [comment]
> json格式错了，第一行删去，空行也删去，json不是代码文件，没有注释这一说

感谢，点赞！！！

**Comment by heshiluodezheshouchang** [comment]
> > json格式错了，第一行删去，空行也删去，json不是代码文件，没有注释这一说
> 
> 感谢，点赞！！！

兄弟，能看看你的json格式不，我的多账号也一直出错，不知道怎么修改，发张图片吧，谢谢兄弟
