### ISSUE TITLE
函数测试时失败

### ISSUE THREAD

**Issue by 1690088023** [ZainCheung/netease-cloud#14]
函数测试失败

**Comment by 1690088023** [comment]
![Uploading 1.PNG…]()

**Comment by 1690088023** [comment]
[Uploading 1.PNG…]()

**Comment by 1690088023** [comment]
这个是失败代码{"errorCode":-1,"errorMessage":"UserCodeError"}

**Comment by ZainCheung** [comment]
新用户初次使用需要对角色授权，允许服务代替用户完成对授权资源的操作。操作步骤见腾讯云官网文档。

**Comment by 1690088023** [comment]
> 新用户初次使用需要对角色授权，允许服务代替用户完成对授权资源的操作。操作步骤见腾讯云官网文档。

好的

**Comment by 1690088023** [comment]
授权了还是一样的啊

**Comment by ZainCheung** [comment]
那可能就是代码有问题，配置账号就行了别改代码，再不行就重新部署一下吧，或者可以问问腾讯云的客服{"errorCode":-1,"errorMessage":"UserCodeError"}的常见场景
