### ISSUE TITLE
用户任务执行中断,请检查账号密码是否正确，求大佬帮我看看

### ISSUE THREAD

**Issue by livchen0523** [ZainCheung/netease-cloud#15]
START RequestId: f063ae89-ba90-4b1b-a2bf-8eca8e1aa763

Event RequestId: f063ae89-ba90-4b1b-a2bf-8eca8e1aa763

配置文件读取完毕

Starting new HTTPS connection (1): netease-livchen-api.glitch.me:443

https://netease-livchen-api.glitch.me:443 "GET /?do=check HTTP/1.1" 200 7601

api测试正常

账号: 13022530718  开始执行========================================

Starting new HTTPS connection (1): netease-livchen-api.glitch.me:443

https://netease-livchen-api.glitch.me:443 "POST /?do=login HTTP/1.1" 405 0

2020.07.29-10:08:37   用户任务执行中断,请检查账号密码是否正确

用户任务执行中断,请检查账号密码是否正确========================================

END RequestId: f063ae89-ba90-4b1b-a2bf-8eca8e1aa763

Report RequestId: f063ae89-ba90-4b1b-a2bf-8eca8e1aa763 Duration:2086ms Memory:64MB MemUsage:19.7305MB

**Comment by livchen0523** [comment]
看了前面几个的解答，按照流程重新操作了一遍还是不行。拜托了！

**Comment by ZainCheung** [comment]
### API没部署好，在浏览器里打开你的API地址返回的页面是这样的：
![ae738J.png](https://s1.ax1x.com/2020/07/29/ae738J.png)
### 而正确部署完成后应当是这样的：
[![NWIt8s.png](https://s1.ax1x.com/2020/06/29/NWIt8s.png)](https://imgchr.com/i/NWIt8s)
### 请确保搭建API的流程与教程一致

**Comment by ZainCheung** [comment]
@livchen0523 可以使用方法二搭建一次，传送门：https://github.com/ZainCheung/netease-cloud-api#%E6%96%B9%E6%B3%95%E4%BA%8C-%E7%9B%B4%E6%8E%A5%E5%A4%8D%E5%88%B6%E9%A1%B9%E7%9B%AE

**Comment by livchen0523** [comment]
好的好的，我去试试。非常感谢！

**Comment by 1690088023** [comment]
我也是这个问问题，这个api是自己搭建的，有时正确，有时错误，我就很懵逼

**Comment by ZainCheung** [comment]
> 我也是这个问问题，这个api是自己搭建的，有时正确，有时错误，我就很懵逼

错误的话可以贴出日志报告

**Comment by 1690088023** [comment]
> > 我也是这个问问题，这个api是自己搭建的，有时正确，有时错误，我就很懵逼
> 
> 错误的话可以贴出日志报告
![捕获](https://user-images.githubusercontent.com/59808553/89012234-6ee59d00-d344-11ea-81a6-ee7c2058afe6.PNG)

**Comment by 1690088023** [comment]
![捕获](https://user-images.githubusercontent.com/59808553/89012291-8a50a800-d344-11ea-8ecd-bfda298aff11.PNG)

**Comment by ZainCheung** [comment]
### @1690088023 你使用的并不是本项目指定的API，在浏览器里打开你的API地址返回的页面是这样的：
[![al8llj.png](https://s1.ax1x.com/2020/07/31/al8llj.png)](https://imgchr.com/i/al8llj)
### 而正确部署完成后应当是这样的：
[![NWIt8s.png](https://s1.ax1x.com/2020/06/29/NWIt8s.png)](https://imgchr.com/i/NWIt8s)
### 请确保使用正确的API

**Comment by 1690088023** [comment]
> ### @1690088023 你使用的并不是本项目指定的API，在浏览器里打开你的API地址返回的页面是这样的：
> [![al8llj.png](https://camo.githubusercontent.com/fd2a3c02a2281069a86bbf5ac9fd2b00e66ca880/68747470733a2f2f73312e617831782e636f6d2f323032302f30372f33312f616c386c6c6a2e706e67)](https://imgchr.com/i/al8llj)
> 
> ### 而正确部署完成后应当是这样的：
> [![NWIt8s.png](https://camo.githubusercontent.com/c5fe601c91568db028122ff6a2ebe8711dcb9979/68747470733a2f2f73312e617831782e636f6d2f323032302f30362f32392f4e57497438732e706e67)](https://imgchr.com/i/NWIt8s)
> 
> ### 请确保使用正确的API

但我对接的是这个网站http：//yhwl.icu/api

**Comment by 1690088023** [comment]
![Screenshot_2020-07-31-17-01-06-117_mark via](https://user-images.githubusercontent.com/59808553/89019134-7199bf80-d34f-11ea-9312-4c0548fcdefd.jpg)

**Comment by ZainCheung** [comment]
### 好的，你的日志有点问题，打卡的请求花费了两分钟最终还失败了，可以给你看一下别人正常状态下的日志
![alywC9.png](https://s1.ax1x.com/2020/07/31/alywC9.png)

**Comment by 1690088023** [comment]
> ### @1690088023 好的，你的日志有点问题，打卡的请求花费了两分钟最终还失败了，可以给你看一下别人正常状态下的日志
> ![alywC9.png](https://camo.githubusercontent.com/2e47848b7dc3392bf0857b27d062b10712709302/68747470733a2f2f73312e617831782e636f6d2f323032302f30372f33312f616c797743392e706e67)

那该怎么办呢？

**Comment by ZainCheung** [comment]
@1690088023 项目代码是没有什么问题的，你再排查排查其他部分吧

**Comment by wzhixian** [comment]
我也遇到了请问解决了没有

**Comment by 1074101366** [comment]
我也遇到了
