### ISSUE TITLE
使用文档

### ISSUE THREAD

**Issue by lingtiao** [ZainCheung/netease-cloud#155]
使用文档链接打不开了，提示Gateway Timeout网关超时

**Comment by ZainCheung** [comment]
> 使用文档链接打不开了，提示Gateway Timeout网关超时
试试
https://zaincheung.github.io/netease-cloud/

**Comment by lingtiao** [comment]
谢谢


陵苕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZainCheung/netease-cloud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月17日(星期一) 上午7:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZainCheung/netease-cloud] 使用文档 (Issue #155)





  
使用文档链接打不开了，提示Gateway Timeout网关超时
 试试
 https://zaincheung.github.io/netease-cloud/
