### ISSUE TITLE
用户任务执行中断,请检查账号密码是否正确

### ISSUE THREAD

**Issue by 55gY** [ZainCheung/netease-cloud#16]
** ###API正常，账号密码也没问题，点测试提示任务中断** 

配置文件读取完毕

Starting new HTTP connection (1): api.55gy.cn:80

http://api.55gy.cn:80 "GET /?do=check HTTP/1.1" 301 162

Starting new HTTPS connection (1): api.55gy.cn:443

https://api.55gy.cn:443 "GET /?do=check HTTP/1.1" 200 None

api测试正常

账号: 151799****  开始执行========================================

Starting new HTTP connection (1): api.55gy.cn:80

http://api.55gy.cn:80 "POST /?do=login HTTP/1.1" 301 162

Starting new HTTPS connection (1): api.55gy.cn:443

https://api.55gy.cn:443 "GET /?do=login HTTP/1.1" 200 None

2020.07.30-01:27:28   用户任务执行中断,请检查账号密码是否正确

用户任务执行中断,请检查账号密码是否正确========================================

**Comment by 55gY** [comment]
已解决，骚瑞。是因为配置的时候开了强制HTTPS。需要HTTP和HTTPS都能访问才运行正常

**Comment by wy1ng** [comment]
> 已解决，骚瑞。是因为配置的时候开了强制HTTPS。需要HTTP和HTTPS都能访问才运行正常

如何配置HTTP？
