### ISSUE TITLE
拉取的用户名乱码，累计播放歌曲反馈回来信息是没开始前的数量

### ISSUE THREAD

**Issue by brightmoon2020** [ZainCheung/netease-cloud#17]
大佬，拉取的用户名乱码，累计播放歌曲反馈回来信息是没开始前的数量，这是什么原因啊？用的云函数
![image](https://user-images.githubusercontent.com/51014585/88872821-b50c0500-d24d-11ea-9973-13799bd57a71.png)

**Comment by ZainCheung** [comment]
累计播放歌曲反馈回来信息是没开始前的数量这一点是没有问题的，因为刷数量需要一段时间，之后你再看就上去了
乱码的话你看微信推送乱码没，没有的话可能是云函数平台的事就不用管他

**Comment by brightboom** [comment]
@ZainCheung  这乱码很奇怪，连微信推送也是乱码的，以为是账号问题，但换了个账号还是如此，然后又试了下你新发布的纠正工具软件，发现连纠正工具的下方拉取到我的用户信息也是乱码的，就很神奇，难道就我一个人这样吗
![image](https://user-images.githubusercontent.com/51014585/88891492-e698c680-d275-11ea-9d01-b9a2237ca4dd.png)

**Comment by brightmoon2020** [comment]
换了个API发现拉取信息正常，后察觉是PHP版本的问题，使用的是5.4版本出现乱码，换回7.4就正常了。

**Comment by brightmoon2020** [comment]
感谢大佬的详细教程，非常详细！感谢！

**Comment by ZainCheung** [comment]
好多人基本上都是用的5.4，既然7.4版本你能用那就用它吧
