### ISSUE TITLE
我用开源NeteaseCloudMusicApi搭建的接口，怎么还是登入不上

### ISSUE THREAD

**Issue by nuyoahaoyun** [ZainCheung/netease-cloud#19]
我自己用开源的NeteaseCloudMusicApi搭建的接口，将里面的调用api参数都修改了，咋还是报错，总登入不上
http://163api.nuyoah.cn:80 "POST /login/cellphone HTTP/1.1" 502 407

2020.08.02-04:34:06   用户任务执行中断,请检查账号密码是否正确

**Comment by ZainCheung** [comment]
他那个登陆接口是明文登陆后在API里进行转Md5，你用Md5登陆相当于转换了两次当然登不上，我不知道你修改NeteaseCloudMusicApi源码改的具体是哪些，但是建议开发阶段使用post模拟请求会方便些，你还没确定接口是否生效就用上了

**Comment by nuyoahaoyun** [comment]
自己用的就是明文密码登入的，自己接口调用用post请求能行，我没改NeteaseCloudMusicApi源码，我只是将你的源码调用参数修改成我接口的参数了，
 估计是我修改参数那里出现问题了
