### ISSUE TITLE
用阿里云配置云函数时，函数入口该怎么写.

### ISSUE THREAD

**Issue by z666666z** [ZainCheung/netease-cloud#2]
报错如下
Response
{
    "errorMessage": "Unable to import module 'index'",
    "errorType": "ImportError",
    "stackTrace": [
        "ImportError: No module named 'index'"
    ]
}

**Comment by z666666z** [comment]
弄好了，谢谢兄弟，没仔细看要用本地文件夹上传。。

**Comment by ZainCheung** [comment]
好的
