### ISSUE TITLE
无法启动项目

### ISSUE THREAD

**Issue by xulingran** [ZainCheung/netease-cloud#20]
请问为什么在宝塔面板的python项目管理器中无法启动项目，没有日志输出。
在ssh用`python3 main.py`也会报错

**Comment by ZainCheung** [comment]
服务器部署：https://zaincheung.gitee.io/netease-cloud/#/python/server
你可以检查一下相关依赖有没有装上，用宝塔部署的时候需要勾选上安装依赖的复选框。
如果不行请粘贴一下你的报错输出。

**Comment by xulingran** [comment]
![微信图片_20200806192731](https://user-images.githubusercontent.com/63037000/89526883-05b9ca00-d81b-11ea-8586-5ec49c0386b0.png)
![微信图片_20200806192739](https://user-images.githubusercontent.com/63037000/89526896-09e5e780-d81b-11ea-95ed-e17d79c83353.png)
以上是服务器配置以及无log的log文件夹。以下为输出
`[root@iz9qxqy10vrazyz netease-cloud-master]# python main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser
[root@iz9qxqy10vrazyz netease-cloud-master]# python3
pyenv: python3: command not found

The `python3' command exists in these Python versions:
  3.7.2`

**Comment by ZainCheung** [comment]
日志文件夹是项目管理器生成的，不用管他，真正的日志文件是`run.log`，见下图最后一个文件
还有你用ssh的报错说找不到这个模块，确保自己安装的是`Python3`，然后装上这个模块，如果对linux命令不熟悉的话建议使用宝塔
![](https://s1.ax1x.com/2020/06/28/Ng6lE6.png)

**Comment by xulingran** [comment]
没有run.log，算了我直接在win上手动运行把，谢谢大佬
