### ISSUE TITLE
为什么几乎每条log都会重复输出一遍，Server酱的推送也是两遍

### ISSUE THREAD

**Issue by kxy09** [ZainCheung/netease-cloud#21]
如图
![QQ截图20200811023740](https://user-images.githubusercontent.com/30567845/89812816-aaba0700-db7b-11ea-8a33-0af209da8210.png)

**Comment by ZainCheung** [comment]
参考一下我的配置:
系统：CentOS 7.3 64位
宝塔：7.3.0
Python项目管理器：1.8
可能是受环境的影响，或者系统中开启了两个程序进程，可以监控一下后台进程

**Comment by kxy09** [comment]
> 参考一下我的配置:
> 系统：CentOS 7.3 64位
> 宝塔：7.3.0
> Python项目管理器：1.8
> 可能是受环境的影响，或者系统中开启了两个程序进程，可以监控一下后台进程

查看后台发现确实是开启了两个进程，重启服务器已解决，感谢
系统：CentOS 8.1
宝塔：7.4.2
Python项目管理器：1.9
