### ISSUE TITLE
腾讯云函数部署，自动定时触发，登录用户名错误

### ISSUE THREAD

**Issue by 8lele** [ZainCheung/netease-cloud#22]
使用腾讯云函数，自动定时触发，查看日志出现账号密码错误，但是手动执行测试之后，提示正常，能完整运行

**Comment by ZainCheung** [comment]
API的问题，自己花两分钟搭建一个就好了

**Comment by 8lele** [comment]
好的，我以为是我自己配置的问题，非常感谢😅

**Comment by Code198** [comment]
怎么搭建，有没有教程？

Zain <notifications@github.com> 于 2020年8月15日 周六 09:50写道：

**Comment by ZainCheung** [comment]
API项目地址：https://github.com/ZainCheung/netease-cloud-api
搭建教程：https://zaincheung.github.io/netease-cloud/#/api/
