### ISSUE TITLE
API搭建正确，提示“用户任务执行中断,请检查账号密码是否正确”

### ISSUE THREAD

**Issue by leonvogle** [ZainCheung/netease-cloud#27]
完整日志内容如下
---------------------------我是分割线---------------------------------
START RequestId: 18dd37b2-512d-4564-b924-3246c8fde6f8

Event RequestId: 18dd37b2-512d-4564-b924-3246c8fde6f8

配置文件读取完毕

Starting new HTTPS connection (1): wangyimusic-api.glitch.me:443

https://wangyimusic-api.glitch.me:443 "GET /?do=check HTTP/1.1" 200 None

api测试正常

账号: 18717139003  开始执行

========================================

Starting new HTTPS connection (1): wangyimusic-api.glitch.me:443

https://wangyimusic-api.glitch.me:443 "POST /?do=login HTTP/1.1" 200 None

2020.08.22-13:56:35   用户任务执行中断,请检查账号密码是否正确

 

END RequestId: 18dd37b2-512d-4564-b924-3246c8fde6f8

Report RequestId: 18dd37b2-512d-4564-b924-3246c8fde6f8 Duration:19542ms Memory:64MB MemUsage:41.121094MB
--------------------------分割线------------------------------
以上内容是日志，我打开了api后是正确的api运行界面
![image](https://user-images.githubusercontent.com/67031508/90957945-6146b180-e4c3-11ea-96b5-a7c50d407d59.png)
目前不知道是什么问题了

**Comment by CShiru** [comment]
我也遇到了这个问题，我上个月还好好的，这几天突然就不行了

**Comment by Saucerman-6617** [comment]
Starting new HTTPS connection (1): github.com:443

https://github.com:443 "POST /ZainCheung/netease-cloud-api/issues/new?do=login HTTP/1.1" 403 None

2020.08.29-05:31:22   用户任务执行中断,请检查账号密码是否正确

**Comment by PHPxian** [comment]
我也是出现这问题  ：用户任务执行中断,请检查账号密码是否正确
明文和 MD5 都显示密码错误，这是什么情况？

**Comment by ZainCheung** [comment]
> 我也是出现这问题 ：用户任务执行中断,请检查账号密码是否正确
> 明文和 MD5 都显示密码错误，这是什么情况？

默认的API接口暂时没法用了，自己搭建一个吧，然后可以参加API征集活动，地址：https://github.com/ZainCheung/netease-cloud-api/issues/31

**Comment by Saucerman-6617** [comment]
按照第二种方法直接复制项目最后弄好了，已经可以实现自动打卡，感谢！！

**Comment by ZainCheung** [comment]
> 按照第二种方法直接复制项目最后弄好了，已经可以实现自动打卡，感谢！！

好的

**Comment by 2604836155** [comment]
> 完整日志内容如下
> ---------------------------我是分割线---------------------------------
> START RequestId: 18dd37b2-512d-4564-b924-3246c8fde6f8
> 
> 事件RequestId：18dd37b2-512d-4564-b924-3246c8fde6f8
> 
> 配置文件读取完毕
> 
> 开始新的HTTPS连接（1）：wangyimusic-api.glitch.me:443
> 
> https://wangyimusic-api.glitch.me:443 “ GET /？do = check HTTP / 1.1” 200无
> 
> api测试正常
> 
> 账号: 18717139003 开始执行
> 
> ========================================
> 
> 开始新的HTTPS连接（1）：wangyimusic-api.glitch.me:443
> 
> https://wangyimusic-api.glitch.me:443 “ POST /？do = login HTTP / 1.1” 200无
> 
> 2020.08.22-13:56:35 用户任务执行中断,请检查账号密码是否正确
> 
> END RequestId：18dd37b2-512d-4564-b924-3246c8fde6f8
> 
> Report RequestId: 18dd37b2-512d-4564-b924-3246c8fde6f8 Duration:19542ms Memory:64MB MemUsage:41.121094MB
> --------------------------分割线------------------------------
> 以上内容是日志，我打开了api后是正确的api运行界面
> ![图片](https://user-images.githubusercontent.com/67031508/90957945-6146b180-e4c3-11ea-96b5-a7c50d407d59.png)
> 目前不知道是什么问题了

请问你解决了这个问题了吗？我现在也有这个情况，是突然发生的。

**Comment by 2604836155** [comment]
> > 按照第二种方法直接复制项目最后弄好了，已经可以实现自动打卡，感谢！！
> 
> 好的

请问你是怎么解决的呢？

**Comment by sxx1314** [comment]
这个有点神奇 我搭建在国内阿里云服务器上的api 提示 
```
用户任务执行中断,请检查账号密码是否正确
```
然后在glitch.me 上搭建了一个api就正常了  XD

**Comment by 2604836155** [comment]
淦！我也是阿里云的机子，另外有个带前端页面的站好像也是用的这套api，也不行了。而且貌似好像有抽风的可能性。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sxx1314 <notifications@github.com&gt;
发送时间: 2020年9月2日 15:24
收件人: ZainCheung/netease-cloud <netease-cloud@noreply.github.com&gt;
抄送: 2604836155 <2604836155@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ZainCheung/netease-cloud] API搭建正确，提示“用户任务执行中断,请检查账号密码是否正确” (#27)

**Comment by sxx1314** [comment]
> 淦！我也是阿里云的机子，另外有个带前端页面的站好像也是用的这套api，也不行了。而且貌似好像有抽风的可能性。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: sxx1314 <notifications@github.com&gt; 发送时间: 2020年9月2日 15:24 收件人: ZainCheung/netease-cloud <netease-cloud@noreply.github.com&gt; 抄送: 2604836155 <2604836155@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[ZainCheung/netease-cloud] API搭建正确，提示“用户任务执行中断,请检查账号密码是否正确” (#27)

前端站用的应该是 nodejs

**Comment by sxx1314** [comment]
> > 这个有点神奇 我搭建在国内阿里云服务器上的api 提示
> > ```
> > 用户任务执行中断,请检查账号密码是否正确
> > ```
> > 
> > 
> > 然后在glitch.me 上搭建了一个api就正常了 XD
> 
> 我试了试在github上搞个接口，日志还是
> Starting new HTTPS connection (1): 2604836155.github.io:443
> 
> https://2604836155.github.io:443 "POST /apitest/?do=login HTTP/1.1" 405 131
> 看来项目真的出问题了
> 
> 2020.09.02-07:56:55 用户任务执行中断,请检查账号密码是否正确

日常抽而已  glitch.me 新搭的也会偶尔出问题   最奇葩的应该是国内的服务器搭建的几乎成功不了

**Comment by sxx1314** [comment]
另外定时任务也有问题  不执行  然后用crontab写了个定时执行任务解决
