### ISSUE TITLE
密码显示错误？

### ISSUE THREAD

**Issue by YuXuanTM** [ZainCheung/netease-cloud#3]
为什么我测试是好的，然后定时他自动运行的时候每天都显示密码错误？

**Comment by zhangrj1993** [comment]
同样出现这个情况 早上9点测试还是可以的 之后不行了

**Comment by ZainCheung** [comment]
因为默认的API大家很多人都在用，，服务量大导致后台崩了，再加上国外的云端平台访问速度本来就慢，所以大家最好还是花费两分钟自建一个API，自己用绝对不会崩，搭建起来超简单。

**Comment by zhangrj1993** [comment]
好的 我自己搭建一下api

**Comment by YuXuanTM** [comment]
谢谢，我去试一试

**Comment by zhangrj1993** [comment]
已经成功了  谢谢了兄弟

**Comment by wy1ng** [comment]
> 已经成功了 谢谢了兄弟

请问怎么自己搭建？

**Comment by ZainCheung** [comment]
> > 已经成功了 谢谢了兄弟
> 
> 请问怎么自己搭建？

README里有教程，三种搭建方法
