### ISSUE TITLE
程序每天执行时间是什么时候

### ISSUE THREAD

**Issue by lunix769** [ZainCheung/netease-cloud#30]
程序每天执行时间是什么时候  服务器搭建的  程序大概什么时间会执行一次 每天凌晨不会自动执行  需要宝塔页面重启

**Comment by ZainCheung** [comment]
按照教程运行程序，如果今天是早八点运行，则每天早八点都会自动执行，不需要再管它，如果发现自己有不一样的地方还请再看下教程核对流程
