### ISSUE TITLE
设置对了，api也没错，一直显示密码错误，啥情况，开关大小写都试过，都不行。

### ISSUE THREAD

**Issue by iloveyou616** [ZainCheung/netease-cloud#31]
START RequestId: e09a5b73-39af-4753-ae11-0c859e582573

Event RequestId: e09a5b73-39af-4753-ae11-0c859e582573

配置文件读取完毕

Starting new HTTP connection (1): www.qiyueliuit.com:80

http://www.qiyueliuit.com:80 "GET /?do=check HTTP/1.1" 200 1358

api测试正常

账号: 17xxxx  开始执行

========================================

Starting new HTTP connection (1): www.qiyueliuit.com:80

http://www.qiyueliuit.com:80 "POST /?do=login HTTP/1.1" 404 140

2020.08.29-15:07:34   用户任务执行中断,请检查账号密码是否正确

 

END RequestId: e09a5b73-39af-4753-ae11-0c859e582573

Report RequestId: e09a5b73-39af-4753-ae11-0c859e582573 Duration:1428ms Memory:64MB MemUsage:19.417969MB

**Comment by ZainCheung** [comment]
你用的API不是项目指定的API，打开后是网易云音乐 NodeJS 版 API。你需要搭建自己的API，几分钟就可以完成。
搭建教程在：https://zaincheung.github.io/netease-cloud/#/api/
看你有服务器可以选择使用第三种方法（服务器）搭建，速度会快些。
另外欢迎参加API征集活动：https://github.com/ZainCheung/netease-cloud-api/issues/31

**Comment by DoveBoy** [comment]
> 你用的API不是项目指定的API，打开后是网易云音乐 NodeJS 版 API。你需要搭建自己的API，几分钟就可以完成。
> 搭建教程在：https://zaincheung.github.io/netease-cloud/#/api/
> 看你有服务器可以选择使用第三种方法（服务器）搭建，速度会快些。
> 另外欢迎参加API征集活动：[ZainCheung/netease-cloud-api#31](https://github.com/ZainCheung/netease-cloud-api/issues/31)

我用的就是项目指定的api，自己搭建的，但是现在也是一直提示账号或密码错误

UTF-8
START RequestId: 32d50d44-c183-490c-a450-0da5439b02f5

Event RequestId: 32d50d44-c183-490c-a450-0da5439b02f5

配置文件读取完毕

Starting new HTTPS connection (1): doveboyxxxxxx-test.glitch.me:443

https://doveboyxxxxxx-test.glitch.me:443 "GET /?do=check HTTP/1.1" 200 None

api测试正常

账号: 136xxxxxxxxx  开始执行

========================================

Starting new HTTPS connection (1): doveboyxxxxxx-test.glitch.me:443

https://doveboyxxxxxx-test.glitch.me:443 "POST /?do=login HTTP/1.1" 200 None

2020.09.03-05:26:50   用户任务执行中断,请检查账号密码是否正确

 

END RequestId: 32d50d44-c183-490c-a450-0da5439b02f5

Report RequestId: 32d50d44-c183-490c-a450-0da5439b02f5 Duration:11356ms Memory:64MB MemUsage:20.000000MB

**Comment by ZainCheung** [comment]
@DoveBoy  你的API没有部署完成，打开后页面提示Project Not Found

**Comment by DoveBoy** [comment]
> @DoveBoy 你的API没有部署完成，打开后页面提示Project Not Found

我是为了不让其他人看到，所以把中间打成了xxx，具体云函数返回的日志我发你ZainCheung@qq.com邮箱了
