### ISSUE TITLE
每天都是“今日共播放0首歌”

### ISSUE THREAD

**Issue by deahui** [ZainCheung/netease-cloud#33]
日志中显示API配置正常，账户信息也能获取到，但每天的打卡都是无效的，实际一首歌也没停，也没签到。
以下是部分日志：
返回数据:

null

日志:

START RequestId: 70abbc08-0921-4023-b365-5bd2a0dfa627

Event RequestId: 70abbc08-0921-4023-b365-5bd2a0dfa627

配置文件读取完毕

Starting new HTTP connection (1): wangyiapi.deahui.com:80

http://wangyiapi.deahui.com:80 "GET /?do=check HTTP/1.1" 200 None

api测试正常

账号: 13776645949  开始执行

========================================
Starting new HTTP connection (1): wangyiapi.deahui.com:80
http://wangyiapi.deahui.com:80 "POST /?do=login HTTP/1.1" 200 None
2020.08.30-01:00:03   登录成功
Starting new HTTP connection (1): wangyiapi.deahui.com:80
http://wangyiapi.deahui.com:80 "POST /?do=sign HTTP/1.1" 200 None
2020.08.30-01:00:03   重复签到
Starting new HTTP connection (1): wangyiapi.deahui.com:80
http://wangyiapi.deahui.com:80 "POST /?do=detail HTTP/1.1" 200 None
2020.08.30-01:00:04   获取用户详情成功
Starting new HTTP connection (1): wangyiapi.deahui.com:80
http://wangyiapi.deahui.com:80 "POST /?do=daka HTTP/1.1" 200 None
2020.08.30-01:00:09   {"code":200,"count":1000}
2020.08.30-01:00:09   第1次打卡成功,即将休眠10秒
Starting new HTTP connection (1): wangyiapi.deahui.com:80
http://wangyiapi.deahui.com:80 "POST /?do=detail HTTP/1.1" 200 None
2020.08.30-01:00:19   获取用户详情成功
2020.08.30-01:00:19   今日已打卡播放0首

**Comment by ZainCheung** [comment]
那是因为每天日推的歌你都听过了，建议使用
https://github.com/ZainCheung/netease-cloud-fastplay
这个项目，更改自己的听歌风格，使日推歌曲都是新的歌曲，便可以解决问题
当天刷完可能看不出效果，第二天再做任务的时候数量就上去了
