### ISSUE TITLE
《已测试》非常好用  良心作者！

### ISSUE THREAD

**Issue by poipoi223** [ZainCheung/netease-cloud#34]
首先感谢 作者 @ZainCheung 

放图：
![1](https://user-images.githubusercontent.com/70302744/91662049-69a87900-eacf-11ea-9a46-7ee374d0906a.PNG)

部署环境：宝塔阿帕奇+php7.0+python任务管理器完美运行

每天VX推送也很方便！

**Comment by poipoi223** [comment]
![1](https://user-images.githubusercontent.com/70302744/91662110-d3c11e00-eacf-11ea-871a-4c49f9c89460.PNG)

**Comment by ZainCheung** [comment]
谢谢肯定，因为个人原因，时间较少，未能对代码整体优化，以及下一个版本的功能尚未完善，挺抱歉的
