### ISSUE TITLE
不支持国际手机号

### ISSUE THREAD

**Issue by David-H-1** [ZainCheung/netease-cloud#35]
我是一个国际留学生也在用网易云音乐但是我没有网易邮箱，绑定的手机号是加拿大的，但是贵项目只支持国内手机号，对于国际学生及海外华人十分不便，请您完善项目以支持国际手机号，谢谢！

**Comment by ZainCheung** [comment]
好的了解，目前项目已经新增了国际手机号登陆（暂时仅限单账号），请使用最新的脚本以及最新的API，国家码的配置依旧在配置文件里，请测试功能是否正常

**Comment by David-H-1** [comment]
好的谢谢作者！ Sent from ProtonMail Mobile On Tue, Sep 1, 2020 at 3:32 AM, Zain <notifications@github.com> wrote:  
好的了解，目前项目已经新增了国际手机号登陆（暂时仅限单账号），请使用最新的脚本以及最新的API，国家码的配置依旧在配置文件里，请测试功能是否正常

**Comment by David-H-1** [comment]
不过我输入了正确的账户和密码，却一直提示账户或密码错误
用户任务执行中断,请检查账号密码是否正确

**Comment by ZainCheung** [comment]
你是用的云函数吧，然后有没有开多人账号

**Comment by David-H-1** [comment]
本地python文件，没有开多人

**Comment by David-H-1** [comment]
并且我自己在glitch上搭建api的时候我的页面一直部署不成功，一直提示504 Gateway Timeout

**Comment by ZainCheung** [comment]
这样说来就是API的问题了，你试试API使用这个：https://163.music.520303.xyz/

**Comment by David-H-1** [comment]
我自己从您的项目上clone的代码，在glitch上建了一个服务器，结果一直无法访问
failed to start application on netease-cloud-level-uprade.glitch.me

This is most likely because your project has a code error.
Check your project logs, fix the error and try again.


要么提示504 Gateway Timeout

**Comment by David-H-1** [comment]
> 这样说来就是API的问题了，你试试API使用这个：https://163.music.520303.xyz/

好使了，谢谢！

**Comment by ZainCheung** [comment]
你的这个服务确实是一直打不开，如果需要搭建的话你用第二种方法直接复制项目，能保证不出错
