### ISSUE TITLE
手机号登录不上了，重试报错如下

### ISSUE THREAD

**Issue by youhunwl** [ZainCheung/netease-cloud#36]
ERROR RequestId:0bce6316-aab2-488d-a696-22d98b6c2855 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 283, in main\n    taskPool()\n  File \"/var/user/index.py\", line 264, in taskPool\n    account = loadJson(\"account.json\")\n  File \"/var/user/index.py\", line 241, in loadJson\n    account = json.load(f)\n  File \"/var/lang/python3/lib/python3.6/json/__init__.py\", line 299, in load\n    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)\n  File \"/var/lang/python3/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 355, in raw_decode\n    obj, end = self.scan_once(s, idx)\njson.decoder.JSONDecodeError: Expecting ',' delimiter: line 12 column 5 (char 305)"}

**Comment by ZainCheung** [comment]
你的account.json文件第十二行应该是少了个逗号------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;游魂&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月2日(星期三) 上午9:32
收件人:&nbsp;&quot;ZainCheung/netease-cloud&quot;<netease-cloud@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ZainCheung/netease-cloud] 手机号登录不上了，重试报错如下 (#36)

**Comment by youhunwl** [comment]
我的天，低级错误低级错误，打扰了抱歉
