### ISSUE TITLE
按教程在阿里云服务器部署好了API用不了

### ISSUE THREAD

**Issue by Ruobo612** [ZainCheung/netease-cloud#37]
我自己在阿里云服务器自己按作者的教程部署好了api，但用不了，提示“用户任务执行中断,请检查账号密码是否正确”然后用作者部署API的第二个方法（博客里面的‘复制服务’）能够正常使用，是否服务器搭建的工程还是有bug？我换另外一个华为的服务器一样方法搭建过API，成功过一次后再也用不了了，用云函数返回的日志如下：（因隐私问题及API域名用个人IP，所以隐去电话跟IP没放出来）

START RequestId: a537fbd7-b326-4b0c-a3c6-0121f4d9db72

Event RequestId: a537fbd7-b326-4b0c-a3c6-0121f4d9db72

配置文件读取完毕

Starting new HTTP connection (1): 123.***.***.***:80

http://123.***.***.***:80 "GET /?do=check HTTP/1.1" 200 None

api测试正常

账号: 191*****552  开始执行

========================================

Starting new HTTP connection (1): 123.57.145.230:80

http://123.***.***.***0:80 "POST /?do=login HTTP/1.1" 200 None

2020.09.04-05:52:44   用户任务执行中断,请检查账号密码是否正确

 

END RequestId: a537fbd7-b326-4b0c-a3c6-0121f4d9db72

Report RequestId: a537fbd7-b326-4b0c-a3c6-0121f4d9db72 Duration:782ms Memory:128MB MemUsage:19.300781MB

**Comment by DoveBoy** [comment]
同样问题出现在腾讯云函数，已经好几天了，开发者没回

**Comment by Ruobo612** [comment]
> 同样问题出现在腾讯云函数，已经好几天了，开发者没回

这个在服务器按作者搭建的api确实不能正常使用，用作者第二个方法还是能正常用的，就是可能有点慢。

**Comment by DoveBoy** [comment]
> > 同样问题出现在腾讯云函数，已经好几天了，开发者没回
> 
> 这个在服务器按作者搭建的api确实不能正常使用，用作者第二个方法还是能正常用的，就是可能有点慢。

昨天就可以了，重新pull request后，glitch手动改个代码就行了

**Comment by Ruobo612** [comment]
> > > 同样问题出现在腾讯云函数，已经好几天了，开发者没回
> > 
> > 这个在服务器按作者搭建的api确实不能正常使用，用作者第二个方法还是能正常用的，就是可能有点慢。
> 
> 昨天就可以了，重新pull request后，glitch手动改个代码就行了

用glitch这个确实没问题，我自己之前用阿里服务器按作者那个方法搭建的确实用不了，也不懂是作者那个源码问题还是我的部署出了问题😂

**Comment by DoveBoy** [comment]
> > > > 同样问题出现在腾讯云函数，已经好几天了，开发者没回
> > > 
> > > 
> > > 这个在服务器按作者搭建的api确实不能正常使用，用作者第二个方法还是能正常用的，就是可能有点慢。
> > 
> > 
> > 昨天就可以了，重新pull request后，glitch手动改个代码就行了
> 
> 用glitch这个确实没问题，我自己之前用阿里服务器按作者那个方法搭建的确实用不了，也不懂是作者那个源码问题还是我的部署出了问题😂

这个我就不知道了，感觉用glitch挺方便，唯一缺点就是fork后需要手动改代码更新以及无法删除project，需要发邮件才能删除
