### ISSUE TITLE
自己搭建的api 密码md5已转换提示密码错误

### ISSUE THREAD

**Issue by Me-x** [ZainCheung/netease-cloud#39]
用第二种搭建api的方法可以调试成功（腾讯云函数）

**Comment by Me-x** [comment]
用昨天更新的api接口项目搭建的接口已经可以用了 。 感谢你的项目，真的很实用 。真心感谢

**Comment by ZainCheung** [comment]
好的，按理说三种方法目前都已经恢复了，只是这次的事故太扯了。。。
