### ISSUE TITLE
 用户任务执行中断,请检查账号密码是否正确

### ISSUE THREAD

**Issue by wangding-wd** [ZainCheung/netease-cloud#4]
返回数据:

null

日志:

START RequestId: 6ccf5eb7-1280-40bd-b249-204d07f02a86

Event RequestId: 6ccf5eb7-1280-40bd-b249-204d07f02a86

配置文件读取完毕

Starting new HTTPS connection (1): github.com:443

https://github.com:443 "GET /wangding-wd/netease-cloud-api.git?do=check HTTP/1.1" 301 162

https://github.com:443 "GET /wangding-wd/netease-cloud-api?do=check HTTP/1.1" 200 None

api测试正常

账号: 185********  开始执行========================================

Starting new HTTPS connection (1): github.com:443

https://github.com:443 "POST /wangding-wd/netease-cloud-api.git?do=login HTTP/1.1" 301 162

https://github.com:443 "GET /wangding-wd/netease-cloud-api?do=login HTTP/1.1" 200 None

2020.07.03-01:58:03   用户任务执行中断,请检查账号密码是否正确

用户任务执行中断,请检查账号密码是否正确========================================

 

END RequestId: 6ccf5eb7-1280-40bd-b249-204d07f02a86

Report RequestId: 6ccf5eb7-1280-40bd-b249-204d07f02a86 Duration:2179ms Memory:64MB MemUsage:20.531250MB

**Comment by ZainCheung** [comment]
https://github.com/wangding-wd/netease-cloud-api.git并不是api地址，只是个git地址，请看README教程

**Comment by wangding-wd** [comment]
已解决

**Comment by jrh520** [comment]
> 已解决

没解决，教我一下可好，留下联系方式？

**Comment by wangding-wd** [comment]
> > 已解决
> 
> 没解决，教我一下可好，留下联系方式？

**Comment by wangding-wd** [comment]
> > 已解决
> 
> 没解决，教我一下可好，留下联系方式？

按照步骤来的吗？

**Comment by jrh520** [comment]
恩。

**Comment by jrh520** [comment]
> > > 已解决
> > 
> > 没解决，教我一下可好，留下联系方式？
> 
> 按照步骤来的吗？

嗯。
