### ISSUE TITLE
9.7日源码腾讯云函数执行失败

### ISSUE THREAD

**Issue by Me-x** [ZainCheung/netease-cloud#41]
![$JOL$Y8E}7B3H9N(8T7IRR7(1)](https://user-images.githubusercontent.com/68915862/92449576-db2da900-f1ec-11ea-81b1-4d3ced70cf97.png)

**Comment by wy1ng** [comment]
跟我一样，提示第2行注释用的那三个单引号缩进问题，像我这种半吊子水平，把2-8行用＃号注释掉了，然后又提示第9行索引错误，我就没辙了，哈哈

**Comment by ZainCheung** [comment]
不好意思，缩进确实有点问题没注意到，现在复制最新的云函数代码运行就可以了

**Comment by Me-x** [comment]
> 跟我一样，提示第2行注释用的那三个单引号缩进问题，像我这种半吊子水平，把2-8行用＃号注释掉了，然后又提示第9行索引错误，我就没辙了，哈哈

我直接看不懂 哈哈

**Comment by Me-x** [comment]
> 不好意思，缩进确实有点问题没注意到，现在复制最新的云函数代码运行就可以了

好的

**Comment by Me-x** [comment]
> 不好意思，缩进确实有点问题没注意到，现在复制最新的云函数代码运行就可以了

好的
