### ISSUE TITLE
2020.9.9号 本地搭建api服务跑播放次数无效

### ISSUE THREAD

**Issue by luengwaiban** [ZainCheung/netease-cloud#42]
自己在电脑本地搭建了php的api项目，晚上和早上各跑了一次播放的接口，接口都返回成功，但是网页端听歌排行数均没有增加，注意到听歌排行的提示：”实际播放时长过短的歌曲将不纳入播放次数“  是不是因为这个导致播放数没有增加？

调用api为：http://test-netease.com/?do=listen&id=5226925370&time=28
结果为
```
{
"code": 200,
"count": 28,
"res": "{\"code\":200,\"data\":\"success\",\"message\":\"\"}"    //网易接口返回的结果，我加了这一行返回
}
```

test-netease.com是我本地的host域名

麻烦作者大大确认一下？感谢~
@ZainCheung

**Comment by FedGk** [comment]
如果是提升升级的听歌数量的话，目前只有听没听过的歌才会计算进去

**Comment by luengwaiban** [comment]
> 如果是提升升级的听歌数量的话，目前只有听没听过的歌才会计算进去

@FedGk 请问一下单纯想刷一下某个歌曲的播放量，也需要没听过的歌才会计算进去吗？最起码的歌曲播放次数没有增加呀

**Comment by ZainCheung** [comment]
这个API目前已经打不开了，也没法测试，如果按照文档上部署API使用软件的话，应该是不会出现问题的

**Comment by luengwaiban** [comment]
@ZainCheung 我的意思是：我按照你的php版本的api项目(netease-cloud-api)，在自己本地搭建了这个这个项目，在调用listen这个接口后，歌曲播放数并没有增加，观察了2天，歌曲播放数目都没有增加，可以帮忙确认一下吗？

**Comment by ZainCheung** [comment]
现在有了更好的解决方案，使用大家捐赠的API，不过最好还是自己在云端搭建一个，本地的话就失去了（全自动）初心了
