### ISSUE TITLE
9日提示账号密码错误

### ISSUE THREAD

**Issue by aLuvletter** [ZainCheung/netease-cloud#44]
无论是否开启了md5，一样提示密码错误~，api已经升级了

**Comment by wy1ng** [comment]
我是提示中断，最新的API和云函数，API就我自己用，也不存在人数过多的情况，超时900秒，最近几天测试都是如此。

![image](https://user-images.githubusercontent.com/46668637/92669722-f7445e00-f344-11ea-825d-cfc4ec749ade.png)

**Comment by aLuvletter** [comment]
> 我也最近出现了问题 请问你解决了吗？

解决了，删除了原先的所有文件，重新下载最新的，py项目也删除重新部署，好了~ 
实在不行，api也重新搞一遍

**Comment by mbskter** [comment]
额我换了个api也解决了 可能是服务器安全性不允许访问啥的 多谢
