### ISSUE TITLE
出现No module named configparser

### ISSUE THREAD

**Issue by wooxiaowei** [ZainCheung/netease-cloud#46]
Traceback (most recent call last):
  File "/www/wwwroot/www.XXXXXX.com/netease-cloud-master/main.py", line 9, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser

**Comment by ZainCheung** [comment]
请使用python3执行，如果需要在python2版本使用，可以参考对应文档修改，参考地址：https://docs.python.org/2/library/configparser.html
或者阅读相关博客：https://www.cjavapy.com/article/501/
