### ISSUE TITLE
自己服务器部署api时修改nginx端口后部署失败

### ISSUE THREAD

**Issue by DLGum** [ZainCheung/netease-cloud#47]
宝塔软件管理-->Nginx管理-->配置修改
把一个listen 80的80改为一个自定义端口。
并在/www/server/panel/vhost/nginx/目录下把三个文件全部修改一遍。
如此修改后部署api后打开子域名失败。
可能原因：服务器有caddy2搭建并且生效中的v2ray。占用了80端口。
解决方法没啥头绪。

**Comment by sxx1314** [comment]
和这程序没有半毛钱关系。是你的nginx配置错误。建议直接用nginx来分流v2ray，即可把所有流量正常通过80/433。
