### ISSUE TITLE
执行了几步之后就提示账号密码错误了

### ISSUE THREAD

**Issue by wy1ng** [ZainCheung/netease-cloud#5]
我是用腾讯云函数，测试正常，第二天再执行的时候执行了前几步，后面就错误了

Starting new HTTPS connection (1): netease-cloud-api.glitch.me:443

https://netease-cloud-api.glitch.me:443 "POST /?do=login HTTP/1.1" 200 None

2020.07.05-00:06:48   登陆成功

登陆成功

Starting new HTTPS connection (1): netease-cloud-api.glitch.me:443

https://netease-cloud-api.glitch.me:443 "POST /?do=sign HTTP/1.1" 200 None

2020.07.05-00:08:27   签到成功

签到成功

Starting new HTTPS connection (1): netease-cloud-api.glitch.me:443

https://netease-cloud-api.glitch.me:443 "POST /?do=detail HTTP/1.1" 504 148

2020.07.05-00:11:28   用户任务执行中断,请检查账号密码是否正确

用户任务执行中断,请检查账号密码是否正确==

**Comment by ZainCheung** [comment]
在你前面的几位提的issue都遇到了这种问题，提问之前麻烦你看一下好么
