### ISSUE TITLE
API搭建正确，提示“用户任务执行中断,请检查账号密码是否正确

### ISSUE THREAD

**Issue by 2990727802** [ZainCheung/netease-cloud#51]
START RequestId: 55932be7-e187-410d-9c6a-695cf69bf083

Event RequestId: 55932be7-e187-410d-9c6a-695cf69bf083

配置文件读取完毕

Starting new HTTP connection (1): neteasecloudmusicapi.zhaoboy.com:80

http://neteasecloudmusicapi.zhaoboy.com:80 "GET /?do=check HTTP/1.1" 200 1107

api测试正常

账号: 15526498790  开始执行========================================

Starting new HTTP connection (1): neteasecloudmusicapi.zhaoboy.com:80

http://neteasecloudmusicapi.zhaoboy.com:80 "POST /?do=login HTTP/1.1" 404 140

2020.10.07-04:30:58   用户任务执行中断,请检查账号密码是否正确

用户任务执行中断,请检查账号密码是否正确========================================

 

END RequestId: 55932be7-e187-410d-9c6a-695cf69bf083

Report RequestId: 55932be7-e187-410d-9c6a-695cf69bf083 Duration:159ms Memory:128MB MemUsage:19.347656MB

**Comment by 2990727802** [comment]
START RequestId: 55932be7-e187-410d-9c6a-695cf69bf083

Event RequestId: 55932be7-e187-410d-9c6a-695cf69bf083

配置文件读取完毕

Starting new HTTP connection (1): neteasecloudmusicapi.zhaoboy.com:80

http://neteasecloudmusicapi.zhaoboy.com:80 "GET /?do=check HTTP/1.1" 200 1107

api测试正常

账号: 15526498790  开始执行========================================

Starting new HTTP connection (1): neteasecloudmusicapi.zhaoboy.com:80

http://neteasecloudmusicapi.zhaoboy.com:80 "POST /?do=login HTTP/1.1" 404 140

2020.10.07-04:30:58   用户任务执行中断,请检查账号密码是否正确

用户任务执行中断,请检查账号密码是否正确========================================

 

END RequestId: 55932be7-e187-410d-9c6a-695cf69bf083

Report RequestId: 55932be7-e187-410d-9c6a-695cf69bf083 Duration:159ms Memory:128MB MemUsage:19.347656MB

**Comment by 2990727802** [comment]
api什么都没错可是就是显示密码错误

**Comment by ZainCheung** [comment]
API搭建的不是项目指定API，正确搭建见：https://zaincheung.github.io/netease-cloud/#/api/
或者使用网友捐赠的公开API，列表地址见：https://zaincheung.github.io/netease-cloud/#/demo/
如果成功搭建好正确的API，浏览器打开API首页应当是这样：
![图片](https://s1.ax1x.com/2020/06/29/NWIt8s.png)

**Comment by 2990727802** [comment]
我用https://netease-cloud-api-sep.glitch.me/也显示
账号: 15526498790  开始执行========================================

Starting new HTTPS connection (1): netease-cloud-api-sep.glitch.me:443

https://netease-cloud-api-sep.glitch.me:443 "POST /?do=login HTTP/1.1" 200 None

2020.10.08-01:34:07   用户任务执行中断,请检查账号密码是否正确

用户任务执行中断,请检查账号密码是否正确========================================

**Comment by wdx6** [comment]
感谢，我用网友捐赠的已经可以政商使用了。再次感谢您的答复，祝您生活愉快。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZainCheung/netease-cloud"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月8日(星期四) 上午8:13
收件人:&nbsp;"ZainCheung/netease-cloud"<netease-cloud@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [ZainCheung/netease-cloud] API搭建正确，提示“用户任务执行中断,请检查账号密码是否正确 (#51)





 
API搭建的不是项目指定API，正确搭建见：https://zaincheung.github.io/netease-cloud/#/api/
 或者使用网友捐赠的公开API，列表地址见：https://zaincheung.github.io/netease-cloud/#/demo/
 如果成功搭建好正确的API，浏览器打开API首页应当是这样：

**Comment by wdx6** [comment]
请尝试更换一下默认的api，目前我用网友捐赠的api已经成功运行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZainCheung/netease-cloud"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月8日(星期四) 上午9:35
收件人:&nbsp;"ZainCheung/netease-cloud"<netease-cloud@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [ZainCheung/netease-cloud] API搭建正确，提示“用户任务执行中断,请检查账号密码是否正确 (#51)





 
我用https://netease-cloud-api-sep.glitch.me/也显示
 账号: 15526498790  开始执行========================================
 
Starting new HTTPS connection (1): netease-cloud-api-sep.glitch.me:443
 
https://netease-cloud-api-sep.glitch.me:443 "POST /?do=login HTTP/1.1" 200 None
 
2020.10.08-01:34:07   用户任务执行中断,请检查账号密码是否正确
 
用户任务执行中断,请检查账号密码是否正确========================================

**Comment by 2990727802** [comment]
更换了网友捐赠的API也一直显示密码错误，就离谱。

**Comment by wdx6** [comment]
你可以尝试一下全部使用小写32位MD5加密
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZainCheung/netease-cloud"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月8日(星期四) 中午11:29
收件人:&nbsp;"ZainCheung/netease-cloud"<netease-cloud@noreply.github.com&gt;;
抄送:&nbsp;"Mr.Wei"<weiup934@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ZainCheung/netease-cloud] API搭建正确，提示“用户任务执行中断,请检查账号密码是否正确 (#51)





 
更换了网友捐赠的API也一直显示密码错误，就离谱。

**Comment by 2990727802** [comment]
改尝试的都尝试了就是不行，一直显示密码错误

**Comment by ZainCheung** [comment]
建议仔细看下项目配置：https://zaincheung.gitee.io/netease-cloud/#/config/
以及常见问题：https://zaincheung.gitee.io/netease-cloud/#/question/
然后自己应该就可以排查出问题所在

**Comment by 2990727802** [comment]
弄好了，把密码前面的空格删掉就没出现错误了，谢了哈

**Comment by sino1641** [comment]
作者默认的api用不了
换文档中其他的api就可以了
与密码字段前的空格无关~

**Comment by T-Y-P** [comment]
我用我自己搭建的api，有10个帐号 第一个成功后面的全部是密码错误

**Comment by xiutu1314** [comment]
2021.04.14-14:12:56   第9次打卡成功,即将休眠10秒

Starting new HTTPS connection (1): siwangq.glitch.me:443

https://siwangq.glitch.me:443 "POST /?do=detail HTTP/1.1" 200 None

2021.04.14-14:13:14   获取用户详情成功

2021.04.14-14:13:14   今日已打卡播放0首

Starting new HTTPS connection (1): sc.ftqq.com:443

https://sc.ftqq.com:443 "GET /SCT30175TnkyCvMERbRJbd5AG5xT3yDDX.send?text=%E7%BD%91%E6%98%93%E4%BA%91%E4%BB%8A%E6%97%A5%E6%89%93%E5%8D%A10%E9%A6%96%EF%BC%8C%E5%B7%B2%E6%92%AD%E6%94%BE13031%E9%A6%96&desp=------%0A%23%23%23%23+%E8%B4%A6%E6%88%B7%E4%BF%A1%E6%81%AF%0A-+%E7%94%A8%E6%88%B7%E5%90%8D%E7%A7%B0%EF%BC%9A%E5%93%A5%E5%93%A5%E6%98%AF%E5%B8%85%E5%A4%A7%E5%8F%94%0A-+%E5%BD%93%E5%89%8D%E7%AD%89%E7%BA%A7%EF%BC%9A9%E7%BA%A7%0A-+%E7%B4%AF%E8%AE%A1%E6%92%AD%E6%94%BE%EF%BC%9A13031%E9%A6%96%0A-+%E5%8D%87%E7%BA%A7%E6%8F%90%E7%A4%BA%EF%BC%9A%E8%BF%98%E9%9C%80%E5%90%AC%E6%AD%8C6969%E9%A6%96%E5%8D%B3%E5%8F%AF%E5%8D%87%E7%BA%A7%0A%0A------%0A%23%23%23%23+%E4%BB%BB%E5%8A%A1%E7%8A%B6%E6%80%81%0A-+%E7%9B%AE%E5%89%8D%E5%B7%B2%E5%AE%8C%E6%88%90%E7%AD%BE%E5%88%B0%0A-+%E4%BB%8A%E6%97%A5%E5%85%B1%E6%89%93%E5%8D%A19%E6%AC%A1%0A-+%E4%BB%8A%E6%97%A5%E5%85%B1%E6%92%AD%E6%94%BE0%E9%A6%96%E6%AD%8C%0A-+%E8%BF%98%E9%9C%80%E8%A6%81%E6%89%93%E5%8D%A124%E5%A4%A9%0A%0A------%0A%23%23%23%23+%E6%89%93%E5%8D%A1%E6%97%A5%E5%BF%97%0A-+%E5%88%9D%E5%A7%8B%E5%8C%96%E5%AE%8C%E6%88%90%0A%0A-+%5B14%3A07%3A41%5D++%E7%99%BB%E5%BD%95%E6%88%90%E5%8A%9F%0A%0A-+%5B14%3A07%3A44%5D++%E9%87%8D%E5%A4%8D%E7%AD%BE%E5%88%B0%0A%0A-+%5B14%3A07%3A49%5D++%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E8%AF%A6%E6%83%85%E6%88%90%E5%8A%9F%0A%0A-+%5B14%3A07%3A59%5D++%7B%22code%22%3A200%2C%22count%22%3A1000%7D%0A%0A-+%5B14%3A07%3A59%5D++%E7%AC%AC1%E6%AC%A1%E6%89%93%E5%8D%A1%E6%88%90%E5%8A%9F%2C%E5%8D%B3%E5%B0%86%E4%BC%91%E7%9C%A010%E7%A7%92%0A%0A-+%5B14%3A08%3A13%5D++%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E8%AF%A6%E6%83%85%E6%88%90%E5%8A%9F%0A%0A-+%5B14%3A08%3A13%5D++%E4%BB%8A%E6%97%A5%E5%B7%B2%E6%89%93%E5%8D%A1%E6%92%AD%E6%94%BE0%E9%A6%96%0A%0A-+%5B14%3A08%3A30%5D++%7B%22code%22%3A200%2C%22count%22%3A1000%7D%0A%0A-+%5B14%3A08%3A30%5D++%E7%AC%AC2%E6%AC%A1%E6%89%93%E5%8D%A1%E6%88%90%E5%8A%9F%2C%E5%8D%B3%E5%B0%86%E4%BC%91%E7%9C%A010%E7%A7%92%0A%0A-+%5B14%3A08%3A45%5D++%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E8%AF%A6%E6%83%85%E6%88%90%E5%8A%9F%0A%0A-+%5B14%3A08%3A45%5D++%E4%BB%8A%E6%97%A5%E5%B7%B2%E6%89%93%E5%8D%A1%E6%92%AD%E6%94%BE0%E9%A6%96%0A%0A-+%5B14%3A08%3A58%5D++%7B%22code%22%3A200%2C%22count%22%3A1000%7D%0A%0A-+%5B14%3A08%3A58%5D++%E7%AC%AC3%E6%AC%A1%E6%89%93%E5%8D%A1%E6%88%90%E5%8A%9F%2C%E5%8D%B3%E5%B0%86%E4%BC%91%E7%9C%A010%E7%A7%92%0A%0A-+%5B14%3A09%3A45%5D++%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E8%AF%A6%E6%83%85%E6%88%90%E5%8A%9F%0A%0A-+%5B14%3A09%3A45%5D++%E4%BB%8A%E6%97%A5%E5%B7%B2%E6%89%93%E5%8D%A1%E6%92%AD%E6%94%BE0%E9%A6%96%0A%0A-+%5B14%3A10%3A12%5D++%7B%22code%22%3A200%2C%22count%22%3A1000%7D%0A%0A-+%5B14%3A10%3A12%5D++%E7%AC%AC4%E6%AC%A1%E6%89%93%E5%8D%A1%E6%88%90%E5%8A%9F%2C%E5%8D%B3%E5%B0%86%E4%BC%91%E7%9C%A010%E7%A7%92%0A%0A-+%5B14%3A10%3A25%5D++%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E8%AF%A6%E6%83%85%E6%88%90%E5%8A%9F%0A%0A-+%5B14%3A10%3A25%5D++%E4%BB%8A%E6%97%A5%E5%B7%B2%E6%89%93%E5%8D%A1%E6%92%AD%E6%94%BE0%E9%A6%96%0A%0A-+%5B14%3A10%3A50%5D++%7B%22code%22%3A200%2C%22count%22%3A1000%7D%0A%0A-+%5B14%3A10%3A50%5D++%E7%AC%AC5%E6%AC%A1%E6%89%93%E5%8D%A1%E6%88%90%E5%8A%9F%2C%E5%8D%B3%E5%B0%86%E4%BC%91%E7%9C%A010%E7%A7%92%0A%0A-+%5B14%3A11%3A04%5D++%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E8%AF%A6%E6%83%85%E6%88%90%E5%8A%9F%0A%0A-+%5B14%3A11%3A04%5D++%E4%BB%8A%E6%97%A5%E5%B7%B2%E6%89%93%E5%8D%A1%E6%92%AD%E6%94%BE0%E9%A6%96%0A%0A-+%5B14%3A11%3A22%5D++%7B%22code%22%3A200%2C%22count%22%3A1000%7D%0A%0A-+%5B14%3A11%3A22%5D++%E7%AC%AC6%E6%AC%A1%E6%89%93%E5%8D%A1%E6%88%90%E5%8A%9F%2C%E5%8D%B3%E5%B0%86%E4%BC%91%E7%9C%A010%E7%A7%92%0A%0A-+%5B14%3A11%3A37%5D++%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E8%AF%A6%E6%83%85%E6%88%90%E5%8A%9F%0A%0A-+%5B14%3A11%3A37%5D++%E4%BB%8A%E6%97%A5%E5%B7%B2%E6%89%93%E5%8D%A1%E6%92%AD%E6%94%BE0%E9%A6%96%0A%0A-+%5B14%3A11%3A52%5D++%7B%22code%22%3A200%2C%22count%22%3A1000%7D%0A%0A-+%5B14%3A11%3A52%5D++%E7%AC%AC7%E6%AC%A1%E6%89%93%E5%8D%A1%E6%88%90%E5%8A%9F%2C%E5%8D%B3%E5%B0%86%E4%BC%91%E7%9C%A010%E7%A7%92%0A%0A-+%5B14%3A12%3A08%5D++%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E8%AF%A6%E6%83%85%E6%88%90%E5%8A%9F%0A%0A-+%5B14%3A12%3A08%5D++%E4%BB%8A%E6%97%A5%E5%B7%B2%E6%89%93%E5%8D%A1%E6%92%AD%E6%94%BE0%E9%A6%96%0A%0A-+%5B14%3A12%3A27%5D++%7B%22code%22%3A200%2C%22count%22%3A1000%7D%0A%0A-+%5B14%3A12%3A27%5D++%E7%AC%AC8%E6%AC%A1%E6%89%93%E5%8D%A1%E6%88%90%E5%8A%9F%2C%E5%8D%B3%E5%B0%86%E4%BC%91%E7%9C%A010%E7%A7%92%0A%0A-+%5B14%3A12%3A42%5D++%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E8%AF%A6%E6%83%85%E6%88%90%E5%8A%9F%0A%0A-+%5B14%3A12%3A42%5D++%E4%BB%8A%E6%97%A5%E5%B7%B2%E6%89%93%E5%8D%A1%E6%92%AD%E6%94%BE0%E9%A6%96%0A%0A-+%5B14%3A12%3A56%5D++%7B%22code%22%3A200%2C%22count%22%3A1000%7D%0A%0A-+%5B14%3A12%3A56%5D++%E7%AC%AC9%E6%AC%A1%E6%89%93%E5%8D%A1%E6%88%90%E5%8A%9F%2C%E5%8D%B3%E5%B0%86%E4%BC%91%E7%9C%A010%E7%A7%92%0A%0A-+%5B14%3A13%3A14%5D++%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E8%AF%A6%E6%83%85%E6%88%90%E5%8A%9F%0A%0A-+%5B14%3A13%3A14%5D++%E4%BB%8A%E6%97%A5%E5%B7%B2%E6%89%93%E5%8D%A1%E6%92%AD%E6%94%BE0%E9%A6%96%0A%0A-+%E6%89%93%E5%8D%A1%E7%BB%93%E6%9D%9F%EF%BC%8C%E6%B6%88%E6%81%AF%E6%8E%A8%E9%80%81%0A%0A%0A%0A HTTP/1.1" 609 1293

2021.04.14-14:13:15   用户任务执行中断,请检查账号密码是否正确

Response RequestId:b9e3ff24-26ff-4c69-b978-5e9188f3676e RetMsg:null

END RequestId:b9e3ff24-26ff-4c69-b978-5e9188f3676e

Report RequestId:b9e3ff24-26ff-4c69-b978-5e9188f3676e Duration:348470ms Memory:64MB MemUsage:48.402344MB

**Comment by xiutu1314** [comment]
每次第十次就会出现上面这样的错误，请问应该怎么解决
