### ISSUE TITLE
An error occurred with this application.

### ISSUE THREAD

**Issue by li666-cpu** [ZainCheung/netease-cloud#57]
自己本地运行，打卡成功后显示这个，无法刷歌
显示  An error occurred with this application.

NO_RESPONSE_FROM_FUNCTION

**Comment by ZainCheung** [comment]
提示这个应用程序发生了错误，但是没有详细到是什么错误，在确保了运行环境没问题的情况下尽可能的自己再调试一下吧。-------- 原始邮件 --------发件人： li666-cpu <notifications@github.com>日期： 2020年10月31日周六 上午9:20收件人： ZainCheung/netease-cloud <netease-cloud@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [ZainCheung/netease-cloud] An error occurred with this application. (#57)

自己本地运行，打卡成功后显示这个，无法刷歌

**Comment by saki-c** [comment]
解决了吗

**Comment by li666-cpu** [comment]
解决了，换一个服务器
