### ISSUE TITLE
api正常，且密碼正確，卻提示「今日已打卡0首」？

### ISSUE THREAD

**Issue by David-H-1** [ZainCheung/netease-cloud#59]
我在UTC時間 2020年11月13日  18:41左右使用 https://api.syhy.ink/netease-cloud/ 嘗試打卡，結果10次打卡一直提示「今日已打卡0首」，日誌如下：
配置文件读取完毕
api测试正常
账号: [private]  开始执行 （賬戶已打碼）
MD5开关已打开,即将开始为你加密,密码不会上传至服务器,请知悉
2020.11.13-18:38:02   登录成功
2020.11.13-18:38:04   重复签到
2020.11.13-18:38:06   获取用户详情成功
2020.11.13-18:38:13   {"code":200,"count":1000}
2020.11.13-18:38:13   第1次打卡成功
2020.11.13-18:38:25   获取用户详情成功
2020.11.13-18:38:25   今日已打卡0首
2020.11.13-18:38:29   {"code":200,"count":1000}
2020.11.13-18:38:30   第2次打卡成功
2020.11.13-18:38:42   获取用户详情成功
2020.11.13-18:38:42   今日已打卡0首
2020.11.13-18:38:46   {"code":200,"count":1000}
2020.11.13-18:38:46   第3次打卡成功
2020.11.13-18:38:58   获取用户详情成功
2020.11.13-18:38:58   今日已打卡0首
2020.11.13-18:39:02   {"code":200,"count":1000}
2020.11.13-18:39:02   第4次打卡成功
2020.11.13-18:39:13   获取用户详情成功
2020.11.13-18:39:13   今日已打卡0首
2020.11.13-18:39:18   {"code":200,"count":1000}
2020.11.13-18:39:18   第5次打卡成功
2020.11.13-18:39:29   获取用户详情成功
2020.11.13-18:39:29   今日已打卡0首
2020.11.13-18:39:33   {"code":200,"count":1000}
2020.11.13-18:39:33   第6次打卡成功
2020.11.13-18:39:45   获取用户详情成功
2020.11.13-18:39:45   今日已打卡0首
2020.11.13-18:39:50   {"code":200,"count":1000}
2020.11.13-18:39:50   第7次打卡成功
2020.11.13-18:40:03   获取用户详情成功
2020.11.13-18:40:03   今日已打卡0首
2020.11.13-18:40:07   {"code":200,"count":1000}
2020.11.13-18:40:07   第8次打卡成功
2020.11.13-18:40:19   获取用户详情成功
2020.11.13-18:40:19   今日已打卡0首
2020.11.13-18:40:23   {"code":200,"count":1000}
2020.11.13-18:40:23   第9次打卡成功
2020.11.13-18:40:35   获取用户详情成功
2020.11.13-18:40:35   今日已打卡0首

請修正該異常，多謝！

**Comment by ShenHai9** [comment]
> 我在UTC時間 2020年11月13日  18:41左右使用 https://api.syhy.ink/netease-cloud/ 嘗試打卡，結果10次打卡一直提示「今日已打卡0首」，日誌如下：
> 
> 配置文件读取完毕
> 
> api测试正常
> 
> 账号: [private]  开始执行 （賬戶已打碼）
> 
> MD5开关已打开,即将开始为你加密,密码不会上传至服务器,请知悉
> 
> 2020.11.13-18:38:02   登录成功
> 
> 2020.11.13-18:38:04   重复签到
> 
> 2020.11.13-18:38:06   获取用户详情成功
> 
> 2020.11.13-18:38:13   {"code":200,"count":1000}
> 
> 2020.11.13-18:38:13   第1次打卡成功
> 
> 2020.11.13-18:38:25   获取用户详情成功
> 
> 2020.11.13-18:38:25   今日已打卡0首
> 
> 2020.11.13-18:38:29   {"code":200,"count":1000}
> 
> 2020.11.13-18:38:30   第2次打卡成功
> 
> 2020.11.13-18:38:42   获取用户详情成功
> 
> 2020.11.13-18:38:42   今日已打卡0首
> 
> 2020.11.13-18:38:46   {"code":200,"count":1000}
> 
> 2020.11.13-18:38:46   第3次打卡成功
> 
> 2020.11.13-18:38:58   获取用户详情成功
> 
> 2020.11.13-18:38:58   今日已打卡0首
> 
> 2020.11.13-18:39:02   {"code":200,"count":1000}
> 
> 2020.11.13-18:39:02   第4次打卡成功
> 
> 2020.11.13-18:39:13   获取用户详情成功
> 
> 2020.11.13-18:39:13   今日已打卡0首
> 
> 2020.11.13-18:39:18   {"code":200,"count":1000}
> 
> 2020.11.13-18:39:18   第5次打卡成功
> 
> 2020.11.13-18:39:29   获取用户详情成功
> 
> 2020.11.13-18:39:29   今日已打卡0首
> 
> 2020.11.13-18:39:33   {"code":200,"count":1000}
> 
> 2020.11.13-18:39:33   第6次打卡成功
> 
> 2020.11.13-18:39:45   获取用户详情成功
> 
> 2020.11.13-18:39:45   今日已打卡0首
> 
> 2020.11.13-18:39:50   {"code":200,"count":1000}
> 
> 2020.11.13-18:39:50   第7次打卡成功
> 
> 2020.11.13-18:40:03   获取用户详情成功
> 
> 2020.11.13-18:40:03   今日已打卡0首
> 
> 2020.11.13-18:40:07   {"code":200,"count":1000}
> 
> 2020.11.13-18:40:07   第8次打卡成功
> 
> 2020.11.13-18:40:19   获取用户详情成功
> 
> 2020.11.13-18:40:19   今日已打卡0首
> 
> 2020.11.13-18:40:23   {"code":200,"count":1000}
> 
> 2020.11.13-18:40:23   第9次打卡成功
> 
> 2020.11.13-18:40:35   获取用户详情成功
> 
> 2020.11.13-18:40:35   今日已打卡0首
> 
> 
> 
> 請修正該異常，多謝！


您好，我是API接口“https://api.syhy.ink/netease-cloud/”的提供者。

經核查，這個API正在正常運作中，且我個人也正在使用該API完成每日打卡任務，暫未發現任何問題。

鑑於您的問題，還煩請您再次確認您的帳號等級數據情況，一般返回打卡成功但今日已打卡0首的情況是因為您帳號今日已完成了聽歌300首的任務，這極有可能是您先前已經完成了一次成功的打卡後再次嘗試打卡所造成的。

至於您所說的，核查帳戶等級數據發現並沒有完成打卡聽歌300首，我個人建議您可以嘗試等待數個小時後再下結論，正如網易雲音樂官方所述“每日聽歌數據可能出現幾小時延遲的情況，帳號等級數據在北京時間下午兩點刷新。”

希望我的回答能夠幫到您，很感謝您使用我提供的接口。

**Comment by David-H-1** [comment]
好的，我稍後重新嘗試一下
我目前的時區是 UTC -08:00 （太平洋標準時間），但是北京時間下午兩點換算成我的時區是22:00（晚上十點），恐怕到時候我得睡覺了。。。

**Comment by David-H-1** [comment]
哦是我這邊的問題，我們這裡下午四時是北京時間次日零時我打卡時是昨天北京的凌晨二時 可能網易官方未更新Sent from ProtonMail Mobile On Fri, Nov 13, 2020 at 12:39 PM, 深海 <notifications@github.com> wrote:  

我在UTC時間 2020年11月13日  18:41左右使用 https://api.syhy.ink/netease-cloud/ 嘗試打卡，結果10次打卡一直提示「今日已打卡0首」，日誌如下：
配置文件读取完毕
api测试正常
账号: [private]  开始执行 （賬戶已打碼）
MD5开关已打开,即将开始为你加密,密码不会上传至服务器,请知悉
2020.11.13-18:38:02   登录成功
2020.11.13-18:38:04   重复签到
2020.11.13-18:38:06   获取用户详情成功
2020.11.13-18:38:13   {"code":200,"count":1000}
2020.11.13-18:38:13   第1次打卡成功
2020.11.13-18:38:25   获取用户详情成功
2020.11.13-18:38:25   今日已打卡0首
2020.11.13-18:38:29   {"code":200,"count":1000}
2020.11.13-18:38:30   第2次打卡成功
2020.11.13-18:38:42   获取用户详情成功
2020.11.13-18:38:42   今日已打卡0首
2020.11.13-18:38:46   {"code":200,"count":1000}
2020.11.13-18:38:46   第3次打卡成功
2020.11.13-18:38:58   获取用户详情成功
2020.11.13-18:38:58   今日已打卡0首
2020.11.13-18:39:02   {"code":200,"count":1000}
2020.11.13-18:39:02   第4次打卡成功
2020.11.13-18:39:13   获取用户详情成功
2020.11.13-18:39:13   今日已打卡0首
2020.11.13-18:39:18   {"code":200,"count":1000}
2020.11.13-18:39:18   第5次打卡成功
2020.11.13-18:39:29   获取用户详情成功
2020.11.13-18:39:29   今日已打卡0首
2020.11.13-18:39:33   {"code":200,"count":1000}
2020.11.13-18:39:33   第6次打卡成功
2020.11.13-18:39:45   获取用户详情成功
2020.11.13-18:39:45   今日已打卡0首
2020.11.13-18:39:50   {"code":200,"count":1000}
2020.11.13-18:39:50   第7次打卡成功
2020.11.13-18:40:03   获取用户详情成功
2020.11.13-18:40:03   今日已打卡0首
2020.11.13-18:40:07   {"code":200,"count":1000}
2020.11.13-18:40:07   第8次打卡成功
2020.11.13-18:40:19   获取用户详情成功
2020.11.13-18:40:19   今日已打卡0首
2020.11.13-18:40:23   {"code":200,"count":1000}
2020.11.13-18:40:23   第9次打卡成功
2020.11.13-18:40:35   获取用户详情成功
2020.11.13-18:40:35   今日已打卡0首
請修正該異常，多謝！

您好，我是API接口“https://api.syhy.ink/netease-cloud/”的提供者。
經核查，這個API正在正常運作中，且我個人也正在使用該API完成每日打卡任務，暫未發現任何問題。
鑑於您的問題，還煩請您再次確認您的帳號等級數據情況，一般返回打卡成功但今日已打卡0首的情況是因為您帳號今日已完成了聽歌300首的任務，這極有可能是您先前已經完成了一次成功的打卡後再次嘗試打卡所造成的。
至於您所說的，核查帳戶等級數據發現並沒有完成打卡聽歌300首，我個人建議您可以嘗試等待數個小時後再下結論，正如網易雲音樂官方所述“每日聽歌數據可能出現幾小時延遲的情況，帳號等級數據在北京時間下午兩點刷新。”
希望我的回答能夠幫到您，很感謝您使用我提供的接口。

**Comment by David-H-1** [comment]
> > 我在UTC時間 2020年11月13日  18:41左右使用 https://api.syhy.ink/netease-cloud/ 嘗試打卡，結果10次打卡一直提示「今日已打卡0首」，日誌如下：
> > 配置文件读取完毕
> > api测试正常
> > 账号: [private]  开始执行 （賬戶已打碼）
> > MD5开关已打开,即将开始为你加密,密码不会上传至服务器,请知悉
> > 2020.11.13-18:38:02   登录成功
> > 2020.11.13-18:38:04   重复签到
> > 2020.11.13-18:38:06   获取用户详情成功
> > 2020.11.13-18:38:13   {"code":200,"count":1000}
> > 2020.11.13-18:38:13   第1次打卡成功
> > 2020.11.13-18:38:25   获取用户详情成功
> > 2020.11.13-18:38:25   今日已打卡0首
> > 2020.11.13-18:38:29   {"code":200,"count":1000}
> > 2020.11.13-18:38:30   第2次打卡成功
> > 2020.11.13-18:38:42   获取用户详情成功
> > 2020.11.13-18:38:42   今日已打卡0首
> > 2020.11.13-18:38:46   {"code":200,"count":1000}
> > 2020.11.13-18:38:46   第3次打卡成功
> > 2020.11.13-18:38:58   获取用户详情成功
> > 2020.11.13-18:38:58   今日已打卡0首
> > 2020.11.13-18:39:02   {"code":200,"count":1000}
> > 2020.11.13-18:39:02   第4次打卡成功
> > 2020.11.13-18:39:13   获取用户详情成功
> > 2020.11.13-18:39:13   今日已打卡0首
> > 2020.11.13-18:39:18   {"code":200,"count":1000}
> > 2020.11.13-18:39:18   第5次打卡成功
> > 2020.11.13-18:39:29   获取用户详情成功
> > 2020.11.13-18:39:29   今日已打卡0首
> > 2020.11.13-18:39:33   {"code":200,"count":1000}
> > 2020.11.13-18:39:33   第6次打卡成功
> > 2020.11.13-18:39:45   获取用户详情成功
> > 2020.11.13-18:39:45   今日已打卡0首
> > 2020.11.13-18:39:50   {"code":200,"count":1000}
> > 2020.11.13-18:39:50   第7次打卡成功
> > 2020.11.13-18:40:03   获取用户详情成功
> > 2020.11.13-18:40:03   今日已打卡0首
> > 2020.11.13-18:40:07   {"code":200,"count":1000}
> > 2020.11.13-18:40:07   第8次打卡成功
> > 2020.11.13-18:40:19   获取用户详情成功
> > 2020.11.13-18:40:19   今日已打卡0首
> > 2020.11.13-18:40:23   {"code":200,"count":1000}
> > 2020.11.13-18:40:23   第9次打卡成功
> > 2020.11.13-18:40:35   获取用户详情成功
> > 2020.11.13-18:40:35   今日已打卡0首
> > 請修正該異常，多謝！
> 
> 您好，我是API接口 https://api.syhy.ink/netease-cloud/ 的提供者。
> 
> 經核查，這個API正在正常運作中，且我個人也正在使用該API完成每日打卡任務，暫未發現任何問題。
> 
> 鑑於您的問題，還煩請您再次確認您的帳號等級數據情況，一般返回打卡成功但今日已打卡0首的情況是因為您帳號今日已完成了聽歌300首的任務，這極有可能是您先前已經完成了一次成功的打卡後再次嘗試打卡所造成的。
> 
> 至於您所說的，核查帳戶等級數據發現並沒有完成打卡聽歌300首，我個人建議您可以嘗試等待數個小時後再下結論，正如網易雲音樂官方所述“每日聽歌數據可能出現幾小時延遲的情況，帳號等級數據在北京時間下午兩點刷新。”
> 
> 希望我的回答能夠幫到您，很感謝您使用我提供的接口。

唔好意思，呢種情況真嘅唔你度嘅問題。咁樣嘅話我將呢個issue閂喇
多謝你提供嘅API!
