### ISSUE TITLE
An error occurred with this application.

### ISSUE THREAD

**Issue by KawasumiXue** [ZainCheung/netease-cloud#63]
配置文件读取完毕
api测试正常
账号:   开始执行
MD5开关已打开,即将开始为你加密,密码不会上传至服务器,请知悉
2020.11.21-20:50:13   登录成功
2020.11.21-20:50:15   签到成功
2020.11.21-20:50:17   获取用户详情成功
2020.11.21-20:50:28   An error occurred with this application.

NO_RESPONSE_FROM_FUNCTION

2020.11.21-20:50:28   第1次打卡成功
2020.11.21-20:50:40   获取用户详情成功
2020.11.21-20:50:40   今日已打卡0首
2020.11.21-20:50:50   An error occurred with this application.

NO_RESPONSE_FROM_FUNCTION

2020.11.21-20:50:50   第2次打卡成功
2020.11.21-20:51:02   获取用户详情成功
2020.11.21-20:51:02   今日已打卡0首
2020.11.21-20:51:11   {"code":200,"count":1000}
2020.11.21-20:51:11   第3次打卡成功
2020.11.21-20:51:23   获取用户详情成功
2020.11.21-20:51:23   今日已打卡34首
2020.11.21-20:51:34   An error occurred with this application.

NO_RESPONSE_FROM_FUNCTION

2020.11.21-20:51:34   第4次打卡成功
2020.11.21-20:51:46   获取用户详情成功
2020.11.21-20:51:46   今日已打卡300首
2020.11.21-20:51:46   用户:  今日任务已完成

**Comment by ZainCheung** [comment]
你好，经排查是第三方API出现了问题，现在已经移除，更新main或index的代码可以正常运行

**Comment by ZainCheung** [comment]
不影响打卡
