### ISSUE TITLE
使用云函数+自建api，没有签到

### ISSUE THREAD

**Issue by Haor** [ZainCheung/netease-cloud#7]
运行后显示签到成功，但是进入app显示没有签到

**Comment by 1299887963** [comment]
It seems like the number of days of landing won't increase, I wonder if anyone else has had similar:)

**Comment by ZainCheung** [comment]
### app的签到和这里的签到并不是同一个，另外如果使用了这个项目后并不能增加每天的听歌数量，或者并没有达到自己预期的300首，那么可以使用另外一个项目：[netease-cloud-fastplay](https://github.com/ZainCheung/netease-cloud-fastplay)。
### 通过增加你喜欢的音乐的播放次数，改变网易云个性化系统中这部分音乐的权重，做到快速纠正自己的听歌偏好，使得网易云推荐的歌曲越来越符合自己的口味。
## 最重要的是，更改听歌领域后不出意外的话每天就会成功刷满300首歌
