### ISSUE TITLE
api测试异常

### ISSUE THREAD

**Issue by noshore** [ZainCheung/netease-cloud#8]
使用云函数出现如下输出是api问题吗 还是我没配置对

START RequestId: e3fe3370-c739-4b94-8e02-ee533d062891

Event RequestId: e3fe3370-c739-4b94-8e02-ee533d062891

配置文件读取完毕

Starting new HTTPS connection (1): netease-cloud-api.glitch.me:443

https://netease-cloud-api.glitch.me:443 "GET /?do=check HTTP/1.1" 503 180

api测试异常

账号: 13205125988  开始执行========================================

Starting new HTTPS connection (1): netease-cloud-api.glitch.me:443

https://netease-cloud-api.glitch.me:443 "POST /?do=login HTTP/1.1" 503 180

2020.07.06-10:31:36   用户任务执行中断,请检查账号密码是否正确

用户任务执行中断,请检查账号密码是否正确

**Comment by keavn** [comment]
俺也一样 第一次可以 后面就报这个错

**Comment by ZainCheung** [comment]
@keavn @noshore 可以看到你们的API用的还是默认API，默认API使用的人比较多所以会打不开，建议及时更改API，可以自己搭建或者寻求其他人的API
![](https://s1.ax1x.com/2020/07/16/UDnDIK.png)
