### ISSUE TITLE
本地执行显示 打卡成功 ，但 今日播放 0 首，实际未增加

### ISSUE THREAD

**Issue by behappy00** [ZainCheung/netease-cloud#82]
![image](https://user-images.githubusercontent.com/38755664/103260157-9fa32e80-49d7-11eb-9ca7-0ba229ecd94b.png)

**Comment by ASSAULT-FOX** [comment]
我也是遇到和你一样的问题

**Comment by behappy00** [comment]
> 我也是遇到和你一样的问题

我没有进行修改，但是两天后就自己好了。现在是时而好用，时而拉跨

**Comment by ASSAULT-FOX** [comment]
> > 我也是遇到和你一样的问题
> 
> 我没有进行修改，但是两天后就自己好了。现在是时而好用，时而拉跨

同样，头两次运行都是没用播放0首，但是之后就成功了，现在倒是稳定运行
